---
- fail:
    msg: "You need at least one parity drive for SnapRAID to work"
  when: array.parity_drives is not defined or array.parity_drives|length == 0

- fail:
    msg: "SnapRAID only supports a maximum of 6 parity drives"
  when: array.parity_drives|length > 6

- fail:
    msg: "You need at least one data drive for SnapRAID to work"
  when: array.data_drives is not defined or array.data_drives|length == 0

- name: "Create SnapRAID configuration folder for array '{{ array.name }}'"
  file:
    path: "{{ array.config_file | dirname }}"
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"

- name: "Push out the SnapRAID configuration file for array '{{ array.name }}'"
  template:
    dest: "{{ array.config_file }}"
    src: snapraid.conf.j2
    mode: '0644'
    owner: "root"
    group: "root"

- name: "Create SnapRAID folder for primary content file for array '{{ array.name }}'"
  file:
    path: "{{ array.primary_content_file | dirname }}"
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
