---
- fail:
    msg: 'You need to define which version of SnapRAID that should be installed (e.g. "11.3")'
  when: snapraid_version is not defined or snapraid_version == ''

- name: Install packages necessary for building and running SnapRAID
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - make
      - mutt
      - logrotate
      - smartmontools
      - unzip

- name: Get the currently installed version of SnapRAID
  shell: snapraid --version | sed -rn 's/snapraid v([0-9]+\.[0-9]+).*$/\1/p'
  register: snapraid_current_version
  check_mode: false
  changed_when: false
  failed_when: >
    (snapraid_current_version.rc != 0)
    and not
    ("snapraid: command not found" in snapraid_current_version.stderr)

- name: Verify that the requested version of SnapRAID is newer than the one installed
  block:
    - fail:
        msg: "The installed version of SnapRAID ({{ snapraid_current_version.stdout }}) is newer than the requested version ({{ snapraid_version }})"
      when: snapraid_current_version.stdout is version(snapraid_version, '>')

    - name: Install new version of SnapRAID
      include: install_snapraid.yml
      when: snapraid_current_version.stdout is version(snapraid_version, '<')
  when: snapraid_current_version.stdout != ''

- name: Install SnapRAID
  include: install_snapraid.yml
  when: snapraid_current_version.stdout == ''

- name: Create folder structure required by 'snapraid_sync'
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: "root"
    group: "root"
  with_items:
    - "{{ snapraid_sync_log_dir }}"
    - "{{ snapraid_sync_script_dir }}"

- name: Push out all files in the 'snapraid_sync' script directory
  copy:
    src: "snapraid_sync/src/"
    dest: "{{ snapraid_sync_script_dir }}"
    mode: '0750'
    owner: "root"
    group: "root"

- name: Configure mutt to be able to send emails over the internet
  template:
    dest: "{{ snapraid_muttrc_path }}"
    src: muttrc.j2
    mode: '0600'
    owner: "root"
    group: "root"
  when: snapraid_sync_email_address is defined

- name: Configure SnapRAID arrays
  include: configure_snapraid.yml array={{ item }}
  with_items: "{{ snapraid_arrays }}"
  when: snapraid_arrays is defined

- name: Push out logrotate configuration for 'snapraid_sync'
  template:
    dest: "/etc/logrotate.d/snapraid_sync"
    src: logrotate_snapraid_sync.j2
    mode: '0600'
    owner: "root"
    group: "root"
