---
- ansible.builtin.fail:
    msg: 'You need to define which version of SnapRAID that should be installed (e.g. "11.3")'
  when: snapraid_version is not defined or snapraid_version == ''

- name: Install packages necessary for building and running SnapRAID
  environment:
    DEBIAN_FRONTEND: noninteractive
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - make
      - mutt
      - logrotate
      - smartmontools
      - unzip

- name: Get the currently installed version of SnapRAID
  ansible.builtin.shell: "snapraid --version"
  check_mode: no
  register: maybe_snapraid_version
  changed_when: false
  failed_when: >
    (
      (maybe_snapraid_version.rc != 0) and not ("not found" in maybe_snapraid_version.stderr)
    )
    or
    (
      (maybe_snapraid_version.rc == 0) and (maybe_snapraid_version.stdout == "")
    )

- name: Extract only the version number from the output
  ansible.builtin.set_fact:
    snapraid_current_version: |-
      {% if 'not found' in maybe_snapraid_version.stderr %}
      {{- '' -}}{# Return empty string in case of no snapraid installed #}
      {% else %}
      {{-
        maybe_snapraid_version.stdout_lines | select('search', 'snapraid v') | first |
        regex_search('^\s*snapraid v([0-9]+\.[0-9]+)\s+.*?$', '\1') | first
      -}}
      {% endif %}

- name: Verify that the requested version of SnapRAID is newer than the one installed
  block:
    - ansible.builtin.fail:
        msg: "The installed version of SnapRAID ({{ snapraid_current_version }}) is newer than the requested version ({{ snapraid_version }})"
      when: snapraid_current_version is version(snapraid_version, '>')

    - name: Install new version of SnapRAID
      ansible.builtin.include_tasks: install_snapraid.yml
      when: snapraid_current_version is version(snapraid_version, '<')
  when: snapraid_current_version != ''

- name: Install SnapRAID
  ansible.builtin.include_tasks: install_snapraid.yml
  when: snapraid_current_version == ''

- name: Create folder structure required by 'snapraid_sync'
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: "root"
    group: "root"
  with_items:
    - "{{ snapraid_sync_log_dir }}"
    - "{{ snapraid_sync_script_dir }}"

- name: Push out all files in the 'snapraid_sync' script directory
  ansible.builtin.copy:
    src: "snapraid_sync/src/"
    dest: "{{ snapraid_sync_script_dir }}"
    mode: '0750'
    owner: "root"
    group: "root"

- name: Configure mutt to be able to send emails over the internet
  ansible.builtin.template:
    dest: "{{ snapraid_muttrc_path }}"
    src: muttrc.j2
    mode: '0600'
    owner: "root"
    group: "root"
  when: snapraid_sync_email_address is defined

- name: Configure SnapRAID arrays
  ansible.builtin.include_tasks: configure_snapraid.yml
  vars:
    array: "{{ item }}"
  with_items: "{{ snapraid_arrays }}"
  when: snapraid_arrays is defined

- name: Push out logrotate configuration for 'snapraid_sync'
  ansible.builtin.template:
    dest: "/etc/logrotate.d/snapraid_sync"
    src: logrotate_snapraid_sync.j2
    mode: '0600'
    owner: "root"
    group: "root"
